### ISSUE TITLE
Can't compile successfully with last ESPhome version (> 2025.11.x)

### ISSUE THREAD

**Issue by SeByDocKy** [anton-malakhov/esphome_webcam#5]
Hi Anton,

I would like to compile your external component... Unfortunatly I am meeting compilation errors with last dev.. with the following yaml:
```
esphome:
  name: esp-webcam
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    # version: 5.5.1
    # platform_version: 55.03.31-2

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source: github://anton-malakhov/esphome_webcam
  
logger:
  level: info
  baud_rate: 0

# Enable Home Assistant API
api:
  batch_delay: 50ms

ota:
  - platform: esphome

time:
  - platform: sntp
    id: my_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HMS Hotspot"
    password: "eVt5yd7PvHjS"  

usb_webcam:
  name: usb-webcam
  ```

Here are the compilation error logs : 
```Compiling .pioenvs\esp-webcam\wifi_provisioning\src\wifi_config.c.o
managed_components\usb_stream\usb_host_helpers.c: In function '_usb_port_init':
managed_components\usb_stream\usb_host_helpers.c:202:10: error: 'hcd_port_config_t' has no member named 'fifo_bias'
  202 |         .fifo_bias = HCD_PORT_FIFO_BIAS_BALANCED,
      |          ^~~~~~~~~
managed_components\usb_stream\usb_host_helpers.c:202:22: error: 'HCD_PORT_FIFO_BIAS_BALANCED' undeclared (first use in this function)
  202 |         .fifo_bias = HCD_PORT_FIFO_BIAS_BALANCED,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
managed_components\usb_stream\usb_host_helpers.c:202:22: note: each undeclared identifier is reported only once for each function it appears in
Compiling .pioenvs\esp-webcam\wifi_provisioning\src\wifi_scan.c.o
*** [.pioenvs\esp-webcam\managed_components\usb_stream\usb_host_helpers.c.o] Error 1
managed_components\usb_stream\usb_stream.c:515:5: error: unknown type name 'hcd_port_fifo_bias_t'; did you mean 'hcd_port_config_t'?
  515 |     hcd_port_fifo_bias_t fifo_bias;
      |     ^~~~~~~~~~~~~~~~~~~~
      |     hcd_port_config_t
In file included from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/esp_intr_alloc.h:12,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/esp_cpu.h:21,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/spinlock.h:11,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\portable\xtensa\include\freertos/portmacro.h:49,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\include/freertos/portable.h:57,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\include/freertos/FreeRTOS.h:69,
                 from managed_components\usb_stream\usb_stream.c:14:
managed_components\usb_stream\usb_stream.c: In function '_usb_processing_task':
managed_components\usb_stream\usb_stream.c:3355:29: error: implicit declaration of function 'hcd_port_set_fifo_bias' [-Wimplicit-function-declaration]
 3355 |             ESP_ERROR_CHECK(hcd_port_set_fifo_bias(usb_dev->port_hdl, usb_dev->fifo_bias));
      |                             ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_common\include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
managed_components\usb_stream\usb_stream.c: In function 'usb_streaming_start':
managed_components\usb_stream\usb_stream.c:3707:27: error: 'HCD_PORT_FIFO_BIAS_BALANCED' undeclared (first use in this function)
 3707 |     s_usb_dev.fifo_bias = HCD_PORT_FIFO_BIAS_BALANCED;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
managed_components\usb_stream\usb_stream.c:3707:27: note: each undeclared identifier is reported only once for each function it appears in
managed_components\usb_stream\usb_stream.c:3761:31: error: 'HCD_PORT_FIFO_BIAS_RX' undeclared (first use in this function)
 3761 |         s_usb_dev.fifo_bias = HCD_PORT_FIFO_BIAS_RX;
```

Kind regards,

Sébastien

**Comment by anton-malakhov** [comment]
I see, the camera API has been changed again. I'll fix it in the next few days

**Comment by anton-malakhov** [comment]
@SeByDocKy The situation is worse than I initially thought. I created branch 'new_esphome' with interface adjustment. But usb_stream component is not aligned with new EspIDF components and is not updated since 2024. Looks like I need to find another USB implementation. Meanwhile, you can try playing with version of IDF where it still works

**Comment by SeByDocKy** [comment]
> [@SeByDocKy](https://github.com/SeByDocKy) The situation is worse than I initially thought. I created branch 'new_esphome' with interface adjustment. But usb_stream component is not aligned with new EspIDF components and is not updated since 2024. Looks like I need to find another USB implementation. Meanwhile, you can try playing with version of IDF where it still works

Yes I know they are abandoning USB_stream in favor of usb_uvc lib..... :( it means to rewrite fully your component with....
The last ESPhome version working with your code is ESPhome@2025.10.4
